services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
    test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
    interval: 10s
    timeout: 5s
    retries: 5

  backend:
    image: ${DOCKERHUB_USER}/${BACKEND_IMAGE}:${BUILD_TAG}
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    ports:
      - "8082:5000"
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    image: ${DOCKERHUB_USER}/${FRONTEND_IMAGE}:${BUILD_TAG}
    ports:
      - "8081:80"
    depends_on:
      - backend

volumes:
  mysql_data:
